name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup-go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: build
        run: go build

  test-openbsd:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: openbsd-vm
        uses: vmactions/openbsd-vm@v1
        with:
          prepare: |
            for i in $(jot 10); do
              echo attempt $i:
              pkg_add -vv go && break
            done
          run: |
            uname -a
            go version
            go build
